### ISSUE TITLE
[linux] FamiStudio freezes

### ISSUE THREAD

**Issue by axredneck** [BleuBleu/FamiStudio#79] opened 2021-06-08 19:56 UTC
It freezes when i close it. It freezes when i open something. It freezes when i press "New project"
Arch Linux, FamiStudio both 3.0 (from Flatpak) and 2.4.2 (`famistudio-bin` from AUR). Also i use Pipewire if it matters.
Terminal output:
```
redneck@pylesos ~> org.famistudio.FamiStudio
Gtk-Message: 22:55:35.477: Failed to load module "canberra-gtk-module"
-:91: Invalid symbolic color 'fg_color'
-:91: error: invalid identifier 'fg_color', expected valid identifier
```

**Comment by BleuBleu** [comment] 2021-06-09 01:58
Hi!

Thanks for reaching out.

The fg_color warning appears on a ton of distribution (FXCE comes to mind) and is a red herring. Its doesn't do anything.

Now back to the other error that i have never seen : canberra-gtk-module. That's an interesting one. But again, i am not sure its relevant. I need to do some googling.

Could you give me a bit of information about your setup so I can try to reproduce this here? (Distro, etc.). Try to think of the simplest setup that would reproduce the issue.

-Mat

**Comment by axredneck** [comment] 2021-06-09 12:02
Arch Linux, KDE, Pipewire, Nvidia proprietary driver... i don't know what can be valuable here.
Maybe you can make some kind of debug build and i will try to crash it on my side?

**Comment by BleuBleu** [comment] 2021-06-10 02:55
Cool. Let me try a distro with Pipewire first. This is the most intriguing one for me.

When you press new or open, the whole audio system gets re-initialized and I have a feeling it gets stuck somehow. Ill try to setup a VM over the weekend. Thanks for your patiente.

-Mat

**Comment by BleuBleu** [comment] 2021-06-11 02:28
So I played with pipewire here, so issues whatsoever. 

As you suggested, I guess the next step would be to send you a debug build with a bunch of random logging so we can try to figure out what's happening. 

Do you happen to be on Discord? I'd prefer to share that privately and not attach some random build here. 

https://discord.gg/88UPmxh

-Mat

**Comment by axredneck** [comment] 2021-06-11 11:10
No, i don't have Discord, but you can send me a build to `otaku at rambler dot ru` email

**Comment by axredneck** [comment] 2021-06-12 15:27
Log of debug build you sent: 
[log.txt](https://github.com/BleuBleu/FamiStudio/files/6642436/log.txt)

**Comment by axredneck** [comment] 2021-06-13 17:41
New log: 
[log.txt](https://github.com/BleuBleu/FamiStudio/files/6644376/log.txt)

**Comment by axredneck** [comment] 2021-06-14 19:23
New log:
[log.txt](https://github.com/BleuBleu/FamiStudio/files/6650740/log.txt)

**Comment by BleuBleu** [comment] 2021-06-15 01:11
Thanks so much for all the testing. Let me share what I know so far, maybe something will make sense to you and you can help me.

These are the audio devices that FamiStudio (well OpenAL, the audio library we use) sees:
* ALSA Default
* USB PnP Sound Device, USB Audio (CARD=Device,DEV=0)
* HDA NVidia, HDMI 0 (CARD=NVidia,DEV=3)
* HDA NVidia, HDMI 1 (CARD=NVidia,DEV=7)
* HDA NVidia, HDMI 2 (CARD=NVidia,DEV=8)
* HDA NVidia, HDMI 3 (CARD=NVidia,DEV=9)
* HDA NVidia, HDMI 4 (CARD=NVidia,DEV=10)
* HDA NVidia, HDMI 5 (CARD=NVidia,DEV=11)
* HD-Audio Generic, ALC892 Analog (CARD=Generic,DEV=0)
* HD-Audio Generic, ALC892 Digital (CARD=Generic,DEV=1)

FamiStudio picks the default one, which is ALSA. But then this device doesn't seem to work correctly. It says its playing sound but its really not processing any audio that FamiStudio gives it. It gets stuck and behaves erratically.

You mentioned Pipewire and im not seeing any of those devices in there? Should it be there? The openal-soft version that i provide with FamiStudio (openal32.so) is only compiled with ALSA support. Do you think thats an issue? Im not sure how ALSA + pipewire are related.

-Mat

**Comment by axredneck** [comment] 2021-06-15 17:28
Usually Pipewire is compatible with ALSA. I have `pipewire-alsa` package installed.
Also i tried to set ALSA as output in Audacious player and it works.
OpenAL works too: GZDoom uses it, and it definitely outputs sound.
> USB PnP Sound Device, USB Audio (CARD=Device,DEV=0)

It's my USB sound card, i use it only for microphone.

> HDA NVidia, HDMI ...

These are Nvidia HDMI output, i use it by default, and `ALSA Default` should mean this output. I don't know why Nvidia proprietary driver has 6 of them.
> HD-Audio Generic ...

It's my motherboard's sound, i don't use it at all.

**Comment by BleuBleu** [comment] 2021-06-16 02:16
Ok thanks for the input.

Im slowly running out of ideas here. One idea is that your system simply doesnt like the openal version i compiled myself. Although i have no clue why that would be the case. 

Let's try to make FamiStudio use the one you probably already have on your system:
1) In the FamiStudio folder, delete (or rename) libopenal32.so
2) Put the OpenTK.dll.config file I included in there (its in the zip fie). 
3) Edit this file so that it points to your open AL soft version you have on your machine already (i assumed it would be libopenal.so but might be slightly different, like libopenal.so.1 or something).
4) Run!

[OpenTK.dll.zip](https://github.com/BleuBleu/FamiStudio/files/6659776/OpenTK.dll.zip)

-Mat

**Comment by axredneck** [comment] 2021-06-16 14:19
Now it works

**Comment by BleuBleu** [comment] 2021-06-17 02:06
Wow! Thats great, but also very unsatisfying since i dont understand the cause of this! 😊

Oh well, ill add this to the "troubleshooting" section of the documentation in the meantime. Once we have more people with the same problem, maybe ill be able to find a pattern and understand the root cause.

Thanks so much for all the debugging. Ill close the issue even if its not really "solved". Reopen if there is anything else not working.

-Mat

**Closed by BleuBleu** 2021-06-17 02:06 UTC

**Comment by BleuBleu** [comment] 2021-06-17 03:06
Added troubleshooting documentation.

https://famistudio.org/doc/troubleshooting/#audio-issues-on-linux

**Comment by axredneck** [comment] 2021-06-17 11:48
> In the FamiStudio folder, delete (or rename) libopenal32.so

It will be harder to do with flatpak version

**Comment by BleuBleu** [comment] 2021-06-17 14:05
That's a good point. Ill get in touch with the guy who setup the flatpak (i didnt do that, i have not clue how it works, i just know how to update it every new release). In theory he should be able to set it up so that it always uses the libopenal.so that you have on your machine.

-Mat

**Comment by BleuBleu** [comment] 2021-06-17 14:22
I just looked at something. The flatpak build is supposed to create a symlink from

libopenal32.so -> /usr/lib/x86_64-linux-gnu/libopenal.so.1 

Did it do that on your end? I wonder why that didnt work...?

-Mat

**Comment by axredneck** [comment] 2021-06-17 16:45
How can i check it?

**Comment by BleuBleu** [comment] 2021-06-18 01:11
That might be the issue. 

If you "ls -l" in the folder where flatpak installs FamiStudio (i have no clue where flatpak installs stuff), you should see a symlink that makes something like this.

libopenal32.so -> /usr/lib/x86_64-linux-gnu/libopenal.so.1

-Mat

**Comment by axredneck** [comment] 2021-06-18 16:13
Yes, i found this link, and it points to non-existing `/usr/lib/x86_64-linux-gnu/libopenal.so.1`

**Comment by axredneck** [comment] 2021-06-20 12:17
Maybe reopen this issue because flatpak version is still affected?

**Comment by BleuBleu** [comment] 2021-06-21 02:50
I have a separate discussion going on on the flatpak page. Although it is not going very well :( Feel free to chime in.

https://github.com/flathub/org.famistudio.FamiStudio/issues/2

-Mat

**Comment by axredneck** [comment] 2022-04-12 21:46
Solved by uninstalling `pipewire-alsa` package. I have no idea why Pipewire tries to use it.

**Comment by axredneck** [comment] 2022-11-18 21:46
Edit: it's not `pipewire-alsa` but `pulseaudio-alsa`, my bad.
