### ISSUE TITLE
HiDPI support on Linux (ChromeOS)

### ISSUE THREAD

**Issue by sirocyl** [BleuBleu/FamiStudio#72] opened 2021-03-11 04:01 UTC
Hey, just reporting in with a minor issue - by default, DPI-awareness seems a bit mixed and moderately broken when running on Linux - specifically, Debian Buster running underneath the "Crostini" virtualization layer,

The Pixelbook's screen is 235ppi (2400x1600 at 12.3").

Here's a screenshot of it running, right at the starting screen.
![Screenshot 2021-03-10 10 00 34 PM](https://user-images.githubusercontent.com/944067/110733769-8b0fbd80-81f4-11eb-967b-05519796d020.png)

**Comment by BleuBleu** [comment] 2021-03-11 04:05
Hey sirocyl, been a while!

Ha yes, Linux is literally the only platform where i didnt bother handling any kind of scaling. One of the issue is that i use a very old version of GTK and cant upgrade at the moment. 😔 

I will see if there is anything i can do, seems like the font are scaling fine. I just need a way to query the current desktop scaling. 

Ill think of something and put that on the list for 2.5.0. Thanks!

-Mat

**Comment by sirocyl** [comment] 2021-03-11 04:09
No problem, glad to hear! I'll do some further testing - if there's any ChromeOS-specific configuration tweaks to help the situation (like, a configuration line in `~/.sommelierrc`, I'll post them in here.

**Comment by sirocyl** [comment] 2021-03-16 13:22
While it's being worked on, if you're working in ChromeOS, you can invoke FamiStudio from the commandline with:
> `sommelier -X --scale=0.66 --dpi=96 --frame-color=#24282c mono FamiStudio.exe`
in the (Linux/crostini-accessible) directory you extracted your FamiStudio distribution into.
(I recommend unzipping the file into `~/famistudio/` or a subdirectory of your home.)

You may also change the scale rate to adjust the effective scaling of the window, text and controls.

**Comment by BleuBleu** [comment] 2021-06-01 13:29
Version 3.0.0 was just released! I had time to include the small bugs you found on Discord. Thanks again for the testing! :) Closing.

**Closed by BleuBleu** 2021-06-01 13:29 UTC
