### ISSUE TITLE
[Linux] Crash on start

### ISSUE THREAD

**Issue by axredneck** [BleuBleu/FamiStudio#107] opened 2022-01-25 14:32 UTC
```
redneck@pylesos ~/p/0/FamiStudio> mono ./FamiStudio.exe
(FamiStudio:24119): Gtk-WARNING **: 17:26:53.226: Загружаемый модуль тем не найден в module_path: «murrine»,
(FamiStudio:24119): Gtk-WARNING **: 17:26:53.226: Загружаемый модуль тем не найден в module_path: «murrine»,
(FamiStudio:24119): Gtk-WARNING **: 17:26:53.226: Загружаемый модуль тем не найден в module_path: «murrine»,
(FamiStudio:24119): Gtk-WARNING **: 17:26:53.227: Загружаемый модуль тем не найден в module_path: «murrine»,
(FamiStudio:24119): Gtk-WARNING **: 17:26:53.227: Загружаемый модуль тем не найден в module_path: «murrine»,
(FamiStudio:24119): Gtk-WARNING **: 17:26:53.228: Загружаемый модуль тем не найден в module_path: «murrine»,
(FamiStudio:24119): Gtk-WARNING **: 17:26:53.228: Загружаемый модуль тем не найден в module_path: «murrine»,
(FamiStudio:24119): Gtk-WARNING **: 17:26:53.228: Загружаемый модуль тем не найден в module_path: «murrine»,
(FamiStudio:24119): Gtk-WARNING **: 17:26:53.228: Загружаемый модуль тем не найден в module_path: «murrine»,
(FamiStudio:24119): Gtk-WARNING **: 17:26:53.228: Загружаемый модуль тем не найден в module_path: «murrine»,
(FamiStudio:24119): Gtk-WARNING **: 17:26:53.229: Загружаемый модуль тем не найден в module_path: «murrine»,
[ALSOFT] (EE) Failed to set real-time priority for thread: Операция не позволена (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Операция не позволена (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Операция не позволена (1)
Default OpenAL audio device is 'JACK Default'
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.ArgumentNullException: Value cannot be null.
Parameter name: stream
  at System.IO.StreamReader..ctor (System.IO.Stream stream, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize, System.Boolean leaveOpen) [0x00021] in <62b430b945fa49a19a75382ef03e7bed>:0
  at System.IO.StreamReader..ctor (System.IO.Stream stream, System.Boolean detectEncodingFromByteOrderMarks) [0x00007] in <62b430b945fa49a19a75382ef03e7bed>:0
  at System.IO.StreamReader..ctor (System.IO.Stream stream) [0x00000] in <62b430b945fa49a19a75382ef03e7bed>:0
  at (wrapper remoting-invoke-with-check) System.IO.StreamReader..ctor(System.IO.Stream)
  at FamiStudio.GLGraphicsBase.CreateFontFromResource (System.String name, System.Boolean bold, System.Int32 size) [0x00063] in <011fe4010ee64969b6993eb29526e4b4>:0
  at FamiStudio.ThemeRenderResources..ctor (FamiStudio.GLGraphics g) [0x00182] in <011fe4010ee64969b6993eb29526e4b4>:0
  at FamiStudio.FamiStudioControls.InitializeGL () [0x00015] in <011fe4010ee64969b6993eb29526e4b4>:0
  at FamiStudio.FamiStudioForm.GLInitialized () [0x0008c] in <011fe4010ee64969b6993eb29526e4b4>:0
  at Gtk.GLWindow.OnExposeEvent (Gdk.EventExpose evnt) [0x001c7] in <011fe4010ee64969b6993eb29526e4b4>:0
  at FamiStudio.FamiStudioForm.OnExposeEvent (Gdk.EventExpose evnt) [0x0001a] in <011fe4010ee64969b6993eb29526e4b4>:0
  at Gtk.Widget.exposeevent_cb (System.IntPtr widget, System.IntPtr evnt) [0x00014] in <e2cf54bd50544b3dbf94649395d8c893>:0
  at GLib.ExceptionManager.RaiseUnhandledException (System.Exception e, System.Boolean is_terminal) [0x00000] in <ed39f21b9e9343dcbd442a17ad356a9f>:0
  at Gtk.Widget.exposeevent_cb (System.IntPtr widget, System.IntPtr evnt) [0x00000] in <e2cf54bd50544b3dbf94649395d8c893>:0
  at Gtk.Application.gtk_main () [0x00000] in <e2cf54bd50544b3dbf94649395d8c893>:0
  at Gtk.Application.Run () [0x00000] in <e2cf54bd50544b3dbf94649395d8c893>:0
  at FamiStudio.FamiStudioForm.Run () [0x00000] in <011fe4010ee64969b6993eb29526e4b4>:0
  at FamiStudio.FamiStudio.Run () [0x00000] in <011fe4010ee64969b6993eb29526e4b4>:0
  at FamiStudio.Program.Main (System.String[] args) [0x00000] in <011fe4010ee64969b6993eb29526e4b4>:0
```
It's Arch Linux and Famistudio 3.2.2 from Github, though `famistudio-bin` from AUR gives the same error.
I can't use Flatpak version due to issue #79.

**Comment by BleuBleu** [comment] 2022-01-25 20:46
Hi. 

I am not supporting the AUR build, this was contributed by a friendly guy on our Discord. You may want to try to get in touch with him. This look like its trying to load a font but not succeeding. 

Like much of those rare crashes, i'm going to apply [the ostrich's algorithm](https://en.wikipedia.org/wiki/Ostrich_algorithm) since those can end up draining an insane amount of time, for very little return. :)

If someone else has something to contribute to this crash, i will leave the bug open.

-Mat

**Comment by axredneck** [comment] 2022-01-26 14:49
> I am not supporting the AUR build

Build from here has exactly the same crash as i already mentioned.

**Comment by mcgrew** [comment] 2022-02-08 00:43
I did some investigation on this but I can't reproduce the error. I tried creating a fresh Arch virtual machine with almost nothing installed but a window manager and famistudio and it worked fine, so it doesn't seem to be a dependency issue. The only advice I can give is make sure all packages are up to date. Beyond that, it must be something with your system configuration or hardware.

**Comment by BleuBleu** [comment] 2022-02-08 02:58
Thanks for looking into this @mcgrew. 

I also gave up a while ago investigating these one-off errors after going through the same process you just did a couple of times (setting up a VM to try to recreate the same environement only to realize that it works fine). You end up sinking an irrational amount of time that would be better spent doing something else. 

I'll keep the bug open, one day, someone will figure out the root cause and report it here.

-Mat

**Comment by yatli** [comment] 2022-05-28 19:21
Run `famistudio` script: same crash.
```
cd /usr/share/famistudio
mono FamiStudio.exe
```
No crash. 🤔

**Comment by BleuBleu** [comment] 2022-08-24 10:54
GTK isnt used anymore in 4.0.0. Closing, re-open another issue if still crashing.

**Closed by BleuBleu** 2022-08-24 10:54 UTC
