### ISSUE TITLE
Error loading project in MonoDeveloper (Linux)

### ISSUE THREAD

**Issue by BombchuLink** [BleuBleu/FamiStudio#20] opened 2020-05-08 23:32 UTC
When loading the .sln file into MonoDev it says:

> Error while trying to load the project '~/FamiStudio/FamiStudio/FamiStudio.Linux.csproj': The type initalizer for 'MonooDevelop.Projects.MSBuild.MSBuildEvaluationContext' threw an exception.

I am running latest version of both MonoDev and have pulled the latest master branch.

neofetch results:

>                    -`                    blink@ArchMasterII
>                   .o+`                   ------------------
>                  `ooo/                   OS: Arch Linux x86_64
>                 `+oooo:                  Host: MS-7A34 1.0
>                `+oooooo:                 Kernel: 5.6.4-arch1-1
>                -+oooooo+:                Uptime: 2 hours, 8 mins
>              `/:-:++oooo+:               Packages: 1201 (pacman)
>             `/++++/+++++++:              Shell: bash 5.0.16
>            `/++++++++++++++:             Resolution: 1920x1080, 1920x1080
>           `/+++ooooooooooooo/`           WM: i3
>          ./ooosssso++osssssso+`          Theme: Arc-Gruvbox [GTK2/3]
>         .oossssso-````/ossssss+`         Icons: Adwaita [GTK2/3]
>        -osssssso.      :ssssssso.        Terminal: st
>       :osssssss/        osssso+++.       Terminal Font: Inconsolata for Powerline
>      /ossssssss/        +ssssooo/-       CPU: AMD Ryzen 7 1700 (16) @ 2.955GHz
>     /ossssso+/:-        -:/+osssso+-     GPU: NVIDIA GeForce GTX 1050 Ti
>     /osssss:-              +osssso+-     Memory: 1946MiB / 16028MiB

**Comment by BleuBleu** [comment] 2020-05-09 01:17
Hi!

I dont think I can be very helpful here unfortunately, i am absolutely not a Linux guru. I opened the Linux solution yesterday without any issues. I googled that error quickly (without FamiStudio in it) and it seems like are not alone with this problem. Can you try to do a bit of research and report back?

Here is the version i am using (their versioning is incredibly confusing as their GitHub uses version 8.x and the releases are 7.x, not sure what's up with that):

> MonoDevelop
> Version 7.8.4 (build 2)
> Installation UUID: 79b6b0ca-2a87-4663-99bd-401b9bd844b0
> 	GTK+ 2.24.32 (Yaru theme)
> 
> Mono Framework MDK
> Runtime:
> 	Mono 6.6.0.161 (tarball Tue Dec 10 10:36:32 UTC 2019) (64-bit)
> 
> NuGet
> Version: 4.8.2.5835
> 
> .NET Core
> Runtime: Not installed
> SDK: Not installed
> MSBuild SDKs: /usr/lib/mono/msbuild/15.0/bin/Sdks
> 
> Build Information
> Release ID: 708040002
> Git revision: 622db12503514afdb641c31615408bfe905a7312
> Build date: 2019-07-17 17:02:07-04
> 
> Operating System
> Linux
> Linux 5.3.0-18-generic #19-Ubuntu SMP Tue Oct 8 20:14:06 UTC 2019 x86_64

-Mat

**Comment by BleuBleu** [comment] 2020-05-15 03:25
No reply from OP in a few days. Closing. I had other people other the solution, no sure what the issue is.

**Closed by BleuBleu** 2020-05-15 03:25 UTC
