### ISSUE TITLE
Window turns invisible when alt-tabbing and the edit song info window is open (Windows 7 SP1)

### ISSUE THREAD

**Issue by cjrobe** [BleuBleu/FamiStudio#19] opened 2020-05-07 22:30 UTC
When you are editing the song info, and you press alt-tab, FamiStudio is cannot be switched to in alt-tab anymore. Screenshots below. The program also crashed afterwards (but does not crash every time. Screenshot and that and full debug info in txt file below as well.

Alt-tab before and after opening song info:
![FamiStudio_R5VAZYpuvU](https://user-images.githubusercontent.com/5606066/81350786-bd123980-9090-11ea-8f6a-604f27a38961.jpg)
![FamiStudio_yy23vcl8Ur](https://user-images.githubusercontent.com/5606066/81350795-c1d6ed80-9090-11ea-9b03-a7a48c65334b.jpg)

Crash screen and dump afterwards:
![FamiStudio_vT2Lm6xPMQ](https://user-images.githubusercontent.com/5606066/81350800-c4394780-9090-11ea-8341-a13d31b39098.jpg)
[debug.txt](https://github.com/BleuBleu/FamiStudio/files/4596095/debug.txt)

**Comment by BleuBleu** [comment] 2020-05-08 01:41
Ok wow. That ive never experience. Ill take a look, i hope i can reproduce this on my ghetto remote machine. And thanks for the "Detail" screenshot, that helps a lot.

-Mat

**Comment by BleuBleu** [comment] 2020-05-08 02:57
Ok, so I looked into it a little bit more. 

1) For the missing window in alt-tab, that's a windows 7 specificity that I wont fix. There are very few people using windows 7 these days, among those, very few are likely to alt-tab at that moment and notice the issue, and if they do, they are likely to not care that much.

2) For the second one, this will actually require some work on my part. Ill put it on the list for 2.1.0. Unfortunately, short of updating to windows 10, i cant propose any workaround for that one at the moment.

-Mat

**Comment by cjrobe** [comment] 2020-05-08 11:27
That's alright - I understand on the Windows 7 part. Thanks for taking a look!

**Comment by BleuBleu** [comment] 2020-05-09 01:28
Hi! 

Can you drop me an email at famistudio@outlook.com, I think I can put a custom build together for both your issues in the next coming days. I just want to send you a build privately, I dont want to put unofficial builds in the wild since they have not been tested very much.

Thanks man.

-Mat

**Comment by BleuBleu** [comment] 2020-05-26 00:23
Fix is included in 2.0.2 which was just released. Thanks again for the bug report and for tying the custom version i sent you!

**Closed by BleuBleu** 2020-05-26 00:23 UTC
